export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const ACCOUNT_FETCH_LOADING = 'ACCOUNT_FETCH_LOADING';
export const ACCOUNT_FETCH_SUCCESS = 'ACCOUNT_FETCH_SUCCESS';
export const ACCOUNT_FETCH_FAIL = 'ACCOUNT_FETCH_FAIL';
export const ACCOUNT_SELECT = 'ACCOUNT_SELECT';

export const CAMPAIGN_FETCH_LOADING = 'CAMPAIGN_FETCH_LOADING';
export const CAMPAIGN_FETCH_SUCCESS = 'CAMPAIGN_FETCH_SUCCESS';
export const CAMPAIGN_FETCH_FAIL = 'CAMPAIGN_FETCH_FAIL';
export const CAMPAIGN_SELECT = 'CAMPAIGN_SELECT';

export const INSIGHT_FETCH_LOADING = 'INSIGHT_FETCH_LOADING';
export const INSIGHT_FETCH_SUCCESS = 'INSIGHT_FETCH_SUCCESS';
export const INSIGHT_FETCH_FAIL = 'INSIGHT_FETCH_FAIL';

export const INSIGHT_BREAKDOWN_FETCH_LOADING = 'INSIGHT_BREAKDOWN_FETCH_LOADING';
export const INSIGHT_BREAKDOWN_FETCH_SUCCESS = 'INSIGHT_BREAKDOWN_FETCH_SUCCESS';
export const INSIGHT_BREAKDOWN_FETCH_FAIL = 'INSIGHT_BREAKDOWN_FETCH_FAIL';
export const INSIGHT_BREAKDOWN_CHANGE_TIME_INCREMENT = 'INSIGHT_BREAKDOWN_CHANGE_TIME_INCREMENT';
export const INSIGHT_BREAKDOWN_FETCH_MORE_SUCCESS = 'INSIGHT_BREAKDOWN_FETCH_MORE_LOADING';
export const INSIGHT_BREAKDOWN_CHANGE_FIELD = 'INSIGHT_BREAKDOWN_CHANGE_FIELD';

export const PROFILE_FETCH_LOADING = 'PROFILE_FETCH_LOADING';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL';

export const VISUAL_PANEL_ADD = 'VISUAL_PANEL_ADD';
export const VISUAL_PANEL_REMOVE = 'VISUAL_PANEL_REMOVE';
export const VISUAL_PANEL_REORDER = 'VISUAL_PANEL_REORDER';
